import { SchematicOptions, PlacementAlgorithm, CircuitSnapshot } from "@tobisk/pcbs/types";
import { registry } from "@tobisk/pcbs/Registry";
import { Component } from "@tobisk/pcbs/Component";
import { Net } from "@tobisk/pcbs/Net";
import { GravityLayout } from "./Layout";

/**
 * Abstract base class for all schematics.
 * 
 * A schematic defines a complete circuit design composed of
 * Nets, Components, Composables, and Modules.
 * 
 * @example
 * ```ts
 * class MyBoard extends Schematic {
 *   generate() {
 *     const vcc = new Net({ name: "VCC", class: "Power" });
 *     const r1 = new Component({ symbol: "Device:R", ref: "R1", footprint: "..." });
 *     r1.pins.A = vcc;
 *   }
 * }
 * export default new MyBoard({ name: "MyBoard" });
 * ```
 */
export abstract class Schematic {
  readonly company: string;
  readonly name: string;
  readonly size: string;
  readonly author: string;
  readonly revision: string;
  readonly description?: string;
  private _layout?: import("./Layout").Layout;
  private _placementAlgorithm?: PlacementAlgorithm;

  constructor(options: SchematicOptions) {
    this.name = options.name;
    this.size = options.size ?? "A4";
    this.author = options.author ?? "";
    this.revision = options.revision ?? "v1.0";
    this.company = options.company ?? "Generated by @tobisk/pcbs";
    this.description = options.description;
    this._layout = options.layout;
    this._placementAlgorithm = options.placementAlgorithm;
  }

  /** Generate the circuit — define all nets, components, and connections. */
  abstract generate(): void;

  /** @internal Generate and capture registered objects */
  _generateWithCapture(): CircuitSnapshot {
    registry.start();
    try {
      this.generate();

      const topLevelItems = registry.getItems().filter((c: any) => !c.parent);

      if (this._layout) {
        this._layout.apply(topLevelItems);
      } else {
        // Auto-layout trigger if any item is unpositioned
        const unpositioned = topLevelItems.filter((i: any) => !i.schematicPosition);
        if (unpositioned.length > 0) {
          new GravityLayout().apply(topLevelItems);
        }
      }
    } finally {
      registry.stop();
    }
    return {
      name: this.name,
      author: this.author,
      revision: this.revision,
      company: this.company,
      description: this.description,
      components: registry.getComponents(),
      nets: registry.getNets(),
      placementAlgorithm: this._placementAlgorithm,
    };
  }
}
